### ISSUE TITLE
'block' cursor type doesnt work in atom 0.176.0

### ISSUE THREAD

**Issue by jeromeetienne** [olmokramer/atom-block-cursor#1]
- all the other types of cursor type work tho

**Comment by olmokramer** [comment]
It works fine for me in 0.176.0. Do you by any chance use a syntax theme that highlights the line the cursor is on?

**Comment by jeromeetienne** [comment]
hmm interesting... thanks for your prompt answer, here is some stuff i remember  
- it stopped working 10min before i filled the issue, while i was relaunching atom.
- i wasnt installing atom packages, or configuring atom
- i was editing a code of my own, i relaunched and the cursor was no more there
  - a pretty noticeable fact when you code :)

This is why i though it was related to a atom update

Just now, i tested to disabled all community atom packages except block cursor, and block cursor is not there. Let me know if there are other tests i can do to help.

**Comment by olmokramer** [comment]
Is there anything in the `block-cursor` object inside `~/.atom/config.cson`? If so, could you post it here?
Thanks!

**Comment by jeromeetienne** [comment]
the config.cson part for 'bordered-box' the one im on right now, working well

```
  "block-cursor":
    primaryColor:
      red: 90
      green: 90
      blue: 90
      alpha: 1
    secondaryColor:
      red: 91
      green: 91
      blue: 91
      alpha: 1
    cursorType: "▯ - bordered-box"
```

the one for when i pick 'block'

```
  "block-cursor":
    primaryColor:
      red: 90
      green: 90
      blue: 90
      alpha: 1
    secondaryColor:
      red: 91
      green: 91
      blue: 91
      alpha: 1
```
