### ISSUE TITLE
Cursor glow effects.

### ISSUE THREAD

**Issue by v3ss0n** [olmokramer/atom-block-cursor#19]
I added this for glowing cursor in your block-cursor package.

I want to contribute but my knowledge of Coffeescript was lacking a lot.
![glow-cursor2](https://cloud.githubusercontent.com/assets/419606/7583649/5299865a-f8bd-11e4-9217-a5ec9789c7bf.png)

Can you give me pointers ? what i wanted to do is add `@cursor-glow` when enabled in setting box, glow effect is based on border color (replace that lightblue with border color ) .  

``` less
@cursor-glow : 0 0 20px 3px fade(lightblue,70%);
atom-text-editor {
  &::shadow .cursors {
    .cursor {
      opacity: 1;
      color: transparent;
      background-color: transparent;
      border: none;
      transition-property: background-color, border-color, opacity;
    }
  }
  .cursor-block &,
  &.cursor-block {
    &::shadow .cursors .cursor {
      z-index: -1;
      box-shadow: @cursor-glow
    }
    &.cursor-line-fix::shadow .cursors .cursor {
      z-index: 1;
      box-shadow: @cursor-glow
    }
  }
  .cursor-bordered-box &,
  &.cursor-bordered-box {
    &::shadow .cursors .cursor {
      border-style: solid;
      box-shadow: @cursor-glow
    }
  }
  .cursor-i-beam &,
  &.cursor-i-beam {
    &::shadow .cursors .cursor {
      border-left-style: solid;
    }
  }
  .cursor-underline &,
  &.cursor-underline {
    &::shadow .cursors .cursor {
      border-bottom-style: solid;
    }
  }
}
atom-text-editor[mini]:not(.is-focused)::shadow .cursors .cursor {
  display: none;
}
```
