### ISSUE TITLE
I can't set a cursor

### ISSUE THREAD

**Issue by timhecker** [olmokramer/atom-block-cursor#22]
After last update (0.13.0) I can't set a cursor (I want i-beam type).

**Comment by olmokramer** [comment]
The settings have changed quite a bit, to allow for more flexibility. I apologize for the inconvenience. For an i-beam cursor you'll have to set the background color to transparent and the border style to i-beam and set a border color.

**Comment by njoannidi** [comment]
Having the same issue. I'm not seeing the options you specify in the config interface. Should we be editing the config.cson or am I missing something?

**Comment by njoannidi** [comment]
Ok, I edited my config.cson with some success to the following:

First find the old "block-cursor" config.
Replaced it with this:

```
   "block-cursor":
    global:
      blinkOn:
        borderStyle: "i-beam"
        borderColor: "#F92"
        backgroundColor: "transparent"
      blinkOff:
         borderStyle: "i-beam"
         borderColor: "#666"
      pulseDuration: 3000
```

Pulse duration doesn't seem to be working, however. Not sure if this is just for I-beam type cursors.
