### ISSUE TITLE
How to bring back pulsating fade in fade out effect?

### ISSUE THREAD

**Issue by v3ss0n** [olmokramer/atom-block-cursor#23]
I am trying multiple ways , but cant do.
also the background color of cursor is opque , is that happened due to tiled rendering? Because before update to 0.13 , it is fine.

**Comment by v3ss0n** [comment]
I think my conf is screwed , i can't configure blink interval or pulse duration at all. Here it is:

```
  "block-cursor":
    preview: "The quick brown fox jumps over the lazy dog"
    global:
      blinkOff:
        borderColor:
          red: 8
          green: 200
          blue: 230
          alpha: 1
        backgroundColor:
          red: 255
          green: 0
          blue: 0
          alpha: 0
        borderStyle: "bordered-box"
      blinkOn:
        borderColor:
          red: 255
          green: 0
          blue: 0
          alpha: 0.15
        backgroundColor:
          red: 0
          green: 0
          blue: 0
          alpha: 0
        borderStyle: "bordered-box"
      pulseDuration: 3000
    primaryColor: {}
    secondaryColor: {}
    blinkInterval: 3000
```
