### ISSUE TITLE
Unable to change borderColor color for blinkOn style

### ISSUE THREAD

**Issue by ikunali** [olmokramer/atom-block-cursor#25]
Version info:
block-cursor: 0.13.1
Atom: 1.0.3

No matter if I change directly in config or via settings, borderColor is not reflecting. It's always coming by default as white. Pls. let me know how to correct it.

Here is how my config looks:

```
"block-cursor":
    selector: "atom-text-editor"
    scopes: [
      "*"
    ]
    blinkOn:
      backgroundColor: "transparent"
      borderStyle: "i-beam"
      borderColor: "red"
      borderWidth: 2
    blinkOff:
      backgroundColor: "transparent"
      borderStyle: "none"
      borderColor: "transparent"
      borderWidth: 1
    pulseDuration: 800
    cursorLineFix: true
    global:
      blinkOn:
        backgroundColor:
          red: 0
          green: 0
          blue: 0
          alpha: 1
        borderColor:
          red: 49
          green: 39
          blue: 233
          alpha: 1
        borderStyle: "i-beam"
        borderWidth: 3
      blinkOff:
        backgroundColor:
          red: 0
          green: 0
          blue: 0
          alpha: 0
        borderStyle: "none"
        borderColor:
          red: 0
          green: 0
          blue: 0
          alpha: 0
      pulseDuration: 900
      cursorLineFix: true
```

**Comment by olmokramer** [comment]
I took the liberty to change that thing into something readable :) Hope you don't mind.

The structure of the config should be:

```
'*':
  'block-cursor':
    'global':
      'blinkOn':
        # blink on styling
      'blinkOff':
        # blink off styling
    'cursorType2':
      'blinkOff':
        # ...
    'cursorType3':
      # ...
```

It looks like you're trying to set the properties directly on the `"block-cursor"` object, though they should be on one of the cursorTypes. Try to override the global style for example:

```
  'block-cursor':
    'global':
      selector: "atom-text-editor"
      scopes: [
        "*"
      ]
      blinkOn:
        backgroundColor: "transparent"
        borderStyle: "i-beam"
        borderColor: "red"
        borderWidth: 2
      blinkOff:
        backgroundColor: "transparent"
        borderStyle: "none"
        borderColor: "transparent"
        borderWidth: 1
      pulseDuration: 800
      cursorLineFix: true
```

I'll see if I can find a better solution for the config in the future, it's quite complicated...
